### ISSUE TITLE
User interaction Flow with zoning pre-reqs steps

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/permit-server#49]
We need to work on the flow for how a user interacts with the zoning district information.
[Residential Express Link
](https://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/Residential_Express_Permit_Application.pdf)
# Overview of how the flow currently is + missing info required to complete the processes before application submission:
- The User gets their application
- The User is told they must do additional reviews on the application
  <img width="767" alt="screen shot 2016-07-16 at 7 49 23 pm" src="https://cloud.githubusercontent.com/assets/10767430/16898084/8a053bbe-4b8e-11e6-858f-3be49bdb7c4a.png">
- The user must then visit a page that is linked in the application to see if they are in a National Registered Historic Zone or a Historic Zone by entering their address and checking a map. _The link in the application takes you to a map that has several overlay options. I can't access the map since it is in Silverlight and I'm having trouble installing the software and getting it to work._ 
- The user must then visit a page that is linked in the application to see if they are in a flood plain. They have to enter their address and check a map.
- The user must then figure out if they are located in an airport overlay zone. Currently, there is no link on where to go to do that _but I assume that is is also on the map that uses Silverlight that I can't view_ 

**Currently, there are no links to the next steps** or other applications that the user must do if are in any of those zones. They have to do a search and figure it out. 
# Missing links & Info

These are the links and to what the user needs in the current flow as shown above
## Historic District
- There is a[ planning and zoning department application page](http://www.austintexas.gov/page/planning-and-zoning-applications#hist) and on it there is a link to a PDF about [historic review application](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/historic-review-nrhd.pdf). 
- They Must then fill out the application for historic review and submit it to the historic preservation office. 
- After review with the service district and they get the okay, they can then submit their application to the permitting department. 
## Flood Plain
- If the user is in a flood zone then they have to check the Watershed Protection Department's page called Floodplain Development Information and see if they qualify for a permit  (http://www.austintexas.gov/page/floodplain-development-information). I should say I have no idea what they are supposed to do here besides click through and read all the link. Need to check in with the permitting department and Julia. 
- The [FAQ page](http://www.austintexas.gov/content/1616/FAQ/2579) is kinda helpful when it comes to doing permitting. 
- If they have a question they can call 512-974-2843 or [send an email to Floodpro](http://www.austintexas.gov/email/floodpro)
## Airport Zone
- There is a section about commercial development that is near the bottom of the above page. It says this 
- If the user is in an airport overlay zone they must visit the [aviation department](http://www.austintexas.gov/resident/aviation). (This is super confusing and idk where they are meant to go )
- My assumption is that they have to visit [this page for the Austin-Bergstrom International Airport](http://www.austintexas.gov/department/doing-business-aus)

> Commercial Development Near the Airport
> For more information:
> David Colligan
> Manager of Global Business Recruitment and Expansion
> Economic Development Department
> City of Austin
> P.O. Box 1088
> Austin, TX 78767
> Direct: 512-974-6381
> Main: 512-974-7819
> Fax: 512-974-7825
> David.Colligan@austintexas.gov
### Expired Permit

<img width="760" alt="screen shot 2016-08-18 at 8 13 01 pm" src="https://cloud.githubusercontent.com/assets/10767430/17795708/437947ba-6580-11e6-8801-3a58702f6805.png">
# Task
- [ ] Figure out where people are to go if they are in a flood plain zone & what they need to do
- [ ] Find out where people are to go if they are in an airport zone and what to do
- [ ] Validate the above information

**Comment by spatialaustin** [comment]
bah--for historical zoning we only have the NRHD layer. Still need the NH and H district areas. i'll track that down.

Also the bit about being within 150 feet of a floodplain means we should buffer that layer to accommodate. Maybe warn people if they are within 500 or 1000ft of the floodplain and wish them good luck with the bureaucracy.

**Comment by twentysixmoons** [comment]
Awesome @spatialaustin. Let us know if you find anything. Are you able to open the silverlite map? There might be info on that mapping page. I can't get it to open though. This is the link : http://www.austintexas.gov/GIS/DevelopmentWebMap/Viewer.aspx

For that second part of your comment I'm taggin @daniellillja , @prestonp , and @vmacdougal so they're aware. 

Will definitely have to catch up with Julia on the airport and floodplain stuff. I don't understand all the way what people are supposed to do if they are in those situations. But if it maps out that they are then we probably have to spit out some text to tell them what to do/where to go next.

**Comment by twentysixmoons** [comment]
Examples of other forms that also need the reviews listed above, for documentation purposes: 
- [Demolition permits](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/demolition_permit_app.pdf) (Also need historic review)
- [Residential review checklist](http://www.austintexas.gov/sites/default/files/files/Planning/residential_review_checklist.pdf)
- [ Fence Application](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/fence_app_AWU.pdf)
- [Residential Interior Remodeling ](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/interiorremod_app.pdf)
- [ Residential new Construction and Addition permit application](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/new_con_addtn_app_AWU.pdf)
- [Residential pool and Uncovered Deck Permit app](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/pool_app_AWU.pdf)
- [Residential Volume Builder Program Building Permit Application](http://www.austintexas.gov/sites/default/files/files/Planning/Applications_Forms/VB_app_AWU.pdf)

...More to come

**Comment by twentysixmoons** [comment]
Got some questions answered by Julia via email recently. As follows:

> Silverlight issue
> 
> I think you might have to use Firefox or IE to interact with the maps.  Whenever I’ve tried to install Silverlight on Chrome, it still doesn’t function.
> 
> Historic District
> 
> This summary looks correct to me.
> 
> For the flood plain check,
> 
> I called the floodplain division to check on this.  Applicants have to go through a floodplain review, but that review is currently built in to our formal plan review process.  Meaning, unlike historic, you don’t have to go talk to another department first.  However, the applicant will be expected to work with that flood plain reviewer to provide relevant information if their application meets certain thresholds (the examples given are submitting a FEMA elevation certificate form 086-0-033 and/or topographic surveys referencing NAVD88). 
> 
> For the Airport overlay check,
> 
> This is similar to above.  There’s nothing required in advance, it’s just a notification that if you’re in the zone, there are certain restrictions on what construction can be done.
